export const SITE_NAME = "Aura Foods";
export const TAGLINE = "Crafted for Pure Taste";
export const PHONE_DISPLAY = "+92 301 2730116";
export const WHATSAPP_NUMBER = "923012730116";
export const BUSINESS_EMAIL = "aurafoodsonline@gmail.com";
export const BUSINESS_CITY = "Karachi";
export const SOCIAL_LINKS = {
  whatsapp: `https://wa.me/${WHATSAPP_NUMBER}`,
  instagram: "https://instagram.com/aurafoodsonline",
  facebook: "https://facebook.com/share/1Ctuc2U2rj/",
  tiktok: "https://tiktok.com/@aurafoodsonline",
  daraz: "https://daraz.pk/shop/d-mall-23/",
};
export const SITE_URL = "https://www.aurafoods.online";

export const DICT = {
  en: {
    dir: "ltr",
    nav_home: "Home", nav_shop: "Shop", nav_about: "About", nav_wholesale: "Wholesale",
    nav_blog: "Blog", nav_faq: "FAQ", nav_contact: "Contact", nav_track: "Track Order",
    nav_cart: "Cart", nav_account: "Account",
    hero_title: "Pure & Premium Organic Spices", hero_sub: "Freshly packed authentic spices, delivered worldwide.",
    hero_badge: "Hand-sourced · Stone-ground · Freshly packed",
    hero_cta: "Shop Now", hero_cta2: "Our Story",
    best_sellers: "Best Sellers", new_arrivals: "New Arrivals", featured: "Featured Products",
    why_title: "Why Aura Foods", view_all: "View All", add_to_cart: "Add to Cart",
    out_of_stock: "Out of Stock", limited_stock: "Limited Stock",
    testimonials: "What Our Customers Say", newsletter_title: "Stay in the Loop",
    footer_tagline: TAGLINE, footer_follow: "Follow Us", footer_contact: "Contact",
    footer_phone: "Phone", footer_email: "Email", footer_rights: "All rights reserved.",
    order_whatsapp: "Order on WhatsApp",
    about_title: "Our Story", about_sub: "From Fresh Fields to Your Spice Rack",
    about_lead: "We trace every spice back to trusted organic family farms.",
    about_h2: "Rooted in Tradition, Trusted Everywhere",
    about_h2_body: "No shortcuts. No additives. Just pure, honest spice that tastes like home.",
    stat_products: "Premium Products", stat_farms: "Partner Farms", stat_promise: "Organic Promise",
    our_values: "Our Values", what_we_stand_for: "What We Stand For",
    contact_title: "Get in Touch", contact_sub: "We'd Love to Hear From You",
    contact_lead: "Questions, wholesale inquiries, or just want to say hello — drop us a message.",
    reach_out: "Reach Out", contact_note: "We typically respond within 24 hours. For urgent orders, please reach out via WhatsApp.",
    full_name: "Full Name", email: "Email", phone: "Phone", message: "Message", send_message: "Send Message",
    address: "Address", chat_whatsapp: "Chat on WhatsApp",
    faq_badge: "Help Center", faq_title: "Frequently Asked Questions",
    faq_sub: "Delivery, returns, refunds, spice storage, and order support.",
    wholesale_badge: "Wholesale & Bulk Orders", wholesale_title: "Authentic Spices at Wholesale Prices",
    wholesale_cta: "Request Bulk Quote on WhatsApp", wholesale_catalog: "Wholesale Catalog",
    wholesale_note: "Every product below is offered in a standard 1kg wholesale pack. Smaller sizes are available in the regular store.",
    track_badge: "Delivery", track_title: "Track Order", track_sub: "Use your order reference and phone number to check delivery status.",
    order_ref: "Order reference", track_btn: "Track", status_label: "Status", delivery_label: "Delivery",
    support_title: "Customer Support", support_sub: "Create a support ticket for orders, delivery, returns, refunds, complaints, or wholesale.",
    category: "Category", subject: "Subject", create_ticket: "Create Ticket",
    not_found_title: "Page Not Found", not_found_body: "The page you're looking for doesn't exist or has been moved.",
    back_home: "Back to Home", browse_spices: "Browse Spices",
    cart_title: "Your Cart", checkout_title: "Checkout", place_order: "Place Order",
    subtotal: "Subtotal", delivery_charges: "Delivery Charges", total: "Total", discount: "Discount",
    payment_method: "Payment Method", cod: "Cash on Delivery",
    reviews: "Customer Reviews", write_review: "Write a Review", verified_purchase: "Verified Purchase",
    submit_review: "Submit Review",
  },
  ur: {
    dir: "rtl",
    nav_home: "ہوم", nav_shop: "شاپ", nav_about: "ہمارے بارے میں", nav_wholesale: "ہول سیل",
    nav_blog: "بلاگ", nav_faq: "سوالات", nav_contact: "رابطہ", nav_track: "آرڈر ٹریک کریں",
    nav_cart: "کارٹ", nav_account: "اکاؤنٹ",
    hero_title: "خالص اور پریمیم آرگینک مصالحے", hero_sub: "تازہ پیک شدہ اصل مصالحے، دنیا بھر میں ڈیلیوری۔",
    hero_badge: "ہاتھ سے چنے گئے · پتھر پر پسے · تازہ پیک",
    hero_cta: "ابھی خریدیں", hero_cta2: "ہماری کہانی",
    best_sellers: "بہترین فروخت", new_arrivals: "نئی آمد", featured: "منتخب مصنوعات",
    why_title: "آورا فوڈز کیوں؟", view_all: "سب دیکھیں", add_to_cart: "کارٹ میں شامل کریں",
    out_of_stock: "سٹاک ختم", limited_stock: "محدود سٹاک",
    testimonials: "ہمارے صارفین کیا کہتے ہیں", newsletter_title: "رابطے میں رہیں",
    footer_tagline: "خالص ذائقے کے لیے تیار کیا گیا", footer_follow: "ہمیں فالو کریں", footer_contact: "رابطہ",
    footer_phone: "فون", footer_email: "ای میل", footer_rights: "جمیع حقوق محفوظ ہیں۔",
    order_whatsapp: "واٹس ایپ پر آرڈر کریں",
    about_title: "ہماری کہانی", about_sub: "تازہ کھیتوں سے آپ کی مصالحہ دان تک",
    about_lead: "ہم ہر مصالحے کو قابلِ اعتماد آرگینک خاندانی کھیتوں تک ٹریس کرتے ہیں۔",
    about_h2: "روایت میں جڑا، ہر جگہ قابلِ اعتماد",
    about_h2_body: "کوئی شارٹ کٹ نہیں۔ کوئی ملاوٹ نہیں۔ صرف خالص اور ایماندار مصالحہ جو گھر جیسا ذائقہ دے۔",
    stat_products: "پریمیم مصنوعات", stat_farms: "پارٹنر فارمز", stat_promise: "آرگینک وعدہ",
    our_values: "ہماری اقدار", what_we_stand_for: "ہم کس چیز کے لیے کھڑے ہیں",
    contact_title: "رابطہ کریں", contact_sub: "ہم آپ سے سننا پسند کریں گے",
    contact_lead: "سوالات، ہول سیل انکوائری، یا صرف سلام کہنا ہو — ہمیں پیغام بھیجیں۔",
    reach_out: "رابطہ کریں", contact_note: "ہم عام طور پر 24 گھنٹوں میں جواب دیتے ہیں۔ فوری آرڈر کے لیے واٹس ایپ پر رابطہ کریں۔",
    full_name: "پورا نام", email: "ای میل", phone: "فون", message: "پیغام", send_message: "پیغام بھیجیں",
    address: "پتہ", chat_whatsapp: "واٹس ایپ پر چیٹ کریں",
    faq_badge: "ہیلپ سینٹر", faq_title: "اکثر پوچھے گئے سوالات",
    faq_sub: "ڈیلیوری، واپسی، رقم کی واپسی، مصالحوں کا ذخیرہ اور آرڈر سپورٹ۔",
    wholesale_badge: "ہول سیل اور بلک آرڈرز", wholesale_title: "ہول سیل قیمتوں پر اصل مصالحے",
    wholesale_cta: "واٹس ایپ پر بلک قیمت کی درخواست کریں", wholesale_catalog: "ہول سیل کیٹلاگ",
    wholesale_note: "نیچے دی گئی ہر پروڈکٹ معیاری 1 کلوگرام ہول سیل پیک میں دستیاب ہے۔",
    track_badge: "ڈیلیوری", track_title: "آرڈر ٹریک کریں", track_sub: "ڈیلیوری کی صورتحال جانچنے کے لیے اپنا آرڈر نمبر اور فون نمبر استعمال کریں۔",
    order_ref: "آرڈر نمبر", track_btn: "ٹریک کریں", status_label: "صورتحال", delivery_label: "ڈیلیوری",
    support_title: "کسٹمر سپورٹ", support_sub: "آرڈر، ڈیلیوری، واپسی، رقم کی واپسی، شکایات یا ہول سیل کے لیے سپورٹ ٹکٹ بنائیں۔",
    category: "قسم", subject: "موضوع", create_ticket: "ٹکٹ بنائیں",
    not_found_title: "صفحہ نہیں ملا", not_found_body: "جو صفحہ آپ تلاش کر رہے ہیں وہ موجود نہیں یا منتقل کر دیا گیا ہے۔",
    back_home: "ہوم پیج پر واپس", browse_spices: "مصالحے دیکھیں",
    cart_title: "آپ کا کارٹ", checkout_title: "چیک آؤٹ", place_order: "آرڈر دیں",
    subtotal: "ذیلی رقم", delivery_charges: "ڈیلیوری چارجز", total: "کل رقم", discount: "رعایت",
    payment_method: "ادائیگی کا طریقہ", cod: "کیش آن ڈیلیوری",
    reviews: "صارفین کے تجربات", write_review: "تجربہ لکھیں", verified_purchase: "تصدیق شدہ خریداری",
    submit_review: "جمع کروائیں",
  },
} as const;

export type Lang = "en" | "ur";
export function t(lang: Lang) {
  return DICT[lang];
}
